kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: scratch-webhook
spec:
  nodeSelector: null
  output: {}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.12-ubi9'
      to:
        kind: ImageStreamTag
        namespace: scratch 
        name: 'scratch-webhook:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/dwnwrd/scratch-webhook.git'
    contextDir: /
  runPolicy: Serial
